### PR TITLE
Extensions to VariableLength: support arrays whose length is determined by another field 

### PR DESCRIPTION
**Pull request by ddasilva**
This change updates the `VariableLength` class to support variable length fields where the length is determined by another field in the packet. For example, you could have fields `data1_len` which sets the length of the `data` array, and then `data2_len` which follows it and sets the length of the `data2` array. I have been told that some instruments generate these types of packets, which were currently unsupported by the `array_shape="expand"` method.

I added a new test for this and all the previous tests pass.  I updated the user's guide for variable length packets and added to the changelog.

```python

   import ccsdspy
   from ccsdspy import PacketField, PacketArray

    pkt = ccsdspy.VariableLength([
         PacketField(
              name='SHCOARSE',
              data_type='uint',
              bit_length=32
         ),
         PacketField(
              name='data_len',
              data_type='uint',
              bit_length=8,
         ),	 
         PacketArray(
              name="data",
              data_type="uint",
              bit_length=16,
              array_shape="data_len",  # links data to data_len
         ),
         PacketField(
              name="checksum",
              data_type="uint",
              bit_length=16
         ),
    ])

### CODE REVIEW

**Comment by ddasilva** [comment]
@ehsteve Let me know what you think of this at a high level. There's a lot of dense code added, no pressure to review it

**Comment by ddasilva** [comment]
Closes #58

**Comment by ddasilva** [comment]
Build of Updated documentation (hidden from public):
https://ccsdspy.readthedocs.io/en/var-length-prev-field/user-guide/variablelength.html

**Comment by ehsteve** [comment]
Hey @ddasilva maybe I'm not understanding something but given that the packet length is already in the ccsds header, isn't it always possible to work out the length of a variable field with this new functionality. Seems to me like any data length field is redundant unless you are relaxing the requirement on having only one expanding field.

**Comment by ddasilva** [comment]
That is correct, you have multiple variable length fields per packet.

**Comment by ddasilva** [comment]
And there is a unit test that does just this!

**Comment by ddasilva** [comment]
I updated the user guide to show the example having two reference-based variable fields, and added a statement to the user guide about how there is not a limit to the number of these reference-based variable fields, but there is for expanding fields.

https://ccsdspy.readthedocs.io/en/var-length-prev-field/user-guide/variablelength.html

**Comment by ddasilva** [comment]
@ehsteve I merged this because several weeks went by and I assumed you didn't have any comments on this. If you have comments, let me know and we can go back to discuss

**Pull request merged**
