### PR TITLE
Packaging update

### PR DESCRIPTION
**Pull request by ehsteve**
This merge request includes

- re-packaging to use the more modern pyproject.toml file. The only tool that cannot use it yet for settings is flake8 so those settings live in `setup.cfg`.
- Uses [setuptools_scm](https://pypi.org/project/setuptools-scm/) to do version numbers automatically using git tags.
- Flake8 compatibility updates
- Updates to the documentation to add release instructions. I can't test the release instructions so I can't vouch for them but i got them from a trusted source.

This replaces my other merge request that used Poetry for packaging.
The repo does not currently have git tags so the first thing to do would be to create a tag in the git history when you made the last release (`0.0.13`). This will then automatically create a version incremented above this to `0.1.13dev`. Your version increments have not been consistent with semantic versioning so far. It should be MAJOR.MINOR.PATCH. where

1. MAJOR version when you make incompatible API changes
2. MINOR version when you add functionality in a backwards compatible manner
3. PATCH version when you make backwards compatible bug fixes

You (and I) have been adding significantly more functionality so the MINOR version should have been increasing. Given that the repo already contains significant functionality and is labeled in Pypi as production stable, i would recommend that you make a release fairly soon with a version number of `1.0.0`. Though technically you are not making breaking changes a `1.0` release is usually interpreted as stable. Additional functionality updates should increment the MINOR version so the next release should be `1.1`

### CODE REVIEW

**Comment by ddasilva** [comment]
Thank you, this is reasonable. I made a 0.0.13 tag just now and pushed it to the repository. The next release can be 1.0.0. I can stick to semantic versioning in the future (I have used semver on other projects, even though I wasn't using it here). I think i'm comfortable with freezing the API for a major release; I don't have any changes I plan on making backwards incompatible any time soon.

It looks like something broke the tests, can you look into that?

**Comment by ddasilva** [comment]
Closes #33 and #42

**Comment by ehsteve** [comment]
Working fixing the tests.

**Comment by ddasilva** [comment]
Looks good to me!

> Oh! and I apologize, i took the liberty of adding myself as an author. Sorry I meant to mention and ask if that was okay beforehand. If you want me to make any changes, just let me know (or if you want me to add anyone else).

I encourage this!

**Comment by ddasilva** [comment]
> Btw, you may want to activate branch protection on main such that it does not allow you to merge without tests passing. There is a way to over-ride it if necessary but it is in red and scary looking ;)

It must have gotten lost when I changed from master to main. I re-enabled this just now

**Pull request merged**
