### PR TITLE
Remove astropy dependency

### LINKED ISSUE #1: Remove dependency on astropy?
Awesome library!

My only critique would be the dependency on astropy for the Table class. Would you consider accepting to remove astropy as a dependency? The only material place astropy appears to be used is here in ccsdspy/interface.py#L108 to wrap the result. I think it would be a little more flexible to allow the user to import astropy.table.Table and wrap the result if they want it wrapped. Astropy is a pretty big dependency to require just for this. 

https://github.com/ddasilva/ccsdspy/blob/7eb6226aa30ca84368c08014466d09436343ce47/ccsdspy/interface.py#L108

### PR DESCRIPTION
**Pull request by 5tefan**
This would resolve #1, remove astropy dependency.

Code and tests updated to remove dependency. Tests passing. 

TODO: have not touched the docs/ yet.

### CODE REVIEW

**Comment by 5tefan** [comment]
I've been very aggressive with the simplification, esp. with a lot of the (what looks to me like) boilerplate from the cookie-cutter import. Feel free to recommend scaling back on that, but, currently, functionality appears to be preserved.

I'll look into adjusting the docs tomorrow.

**Comment by ddasilva** [comment]
Thanks Stefan! I appreciate the support. I'm definitely open to this if you can clear references to astropy on the docs. It should be enough to make the docs use the alabaster theme and make it so grep returns nothing for 'astropy'. Originally I was trying to integrate with astropy so I could apply to be an affiliated package and be listed on the website, but I've since lost interest. I agree this is a step in the right direction, let's bump the version up to 0.0.8 for this.

Feel free to list yourself as a co-author in the `setup.py` if you so fancy.

**Comment by 5tefan** [comment]
Great. I think docs are resolved. Outside of .git/ the only mention of astro is now in the changelog via `grep -r -i "astro" .`. 

I'll leave you as the sole author :) all I've really done is delete stuff. Again, thanks for making this open source!

**Comment by 5tefan** [comment]
Actually, one final item: README says this is under Apache License, but the license I'm finding under licenses/ (this PR would move it to top level) looks to me like a BSD 3 clause. I specified BSD in the setup.py classifiers section. Just wanted to confirm -- this is BSD licensed? If so, should change README.

**Comment by ddasilva** [comment]
Oops! As far as I know BSD and Apache are compatible licenses so this shouldn't be a big deal. Let's go with Apache since that was more visible. I'll take care of that myself.

**Pull request merged**
